WIP: feature(examples): add examples for easier head start
owid/etl pull request #126
Opened 2022-03-18 09:37 UTC by Marigold

TBD

2022-03-23 10:32 UTC, larsyencken requested changes
I'd suggest having the `Catalog().find()` examples use the local catalog instead of the remote one. Other than that, it looks good.

2022-03-25 08:25 UTC, Marigold commented
> I'd suggest having the `Catalog().find()` examples use the local catalog instead of the remote one. Other than that, it looks good.

I don't get it, `Catalog().find()` is **walden's catalog**, not owid-catalog-py's, and uses local catalog. Or maybe I misunderstood this completely?

2022-03-28 11:23 UTC, larsyencken commented
> I don't get it, `Catalog().find()` is **walden's catalog**, not owid-catalog-py's, and uses local catalog. `LocalCatalog/RemoteCatalog` is in owid-catalog-py and I'm not using it at all (instead I'm using `Dataset(...)` to get local version). Or maybe I misunderstood this completely?

You're totally right, I just got confused. This is good to ship then!

(one day we should rename Walden's API to make it less confusing. Perhaps `Catalog -> Walden` and `Dataset -> Snapshot`?)

2022-03-28 11:23 UTC, larsyencken approved these changes

2022-03-28 13:53 UTC, merged